export const RECEIVE_JOB_DATA = 'RECEIVE_JOB_DATA';
export const RECEIVE_ACTION_DATA = 'RECEIVE_ACTION_DATA';
export const RECEIVE_JOB_ACTIONS = 'RECEIVE_JOB_ACTIONS';
export const RECEIVE_CHARACTER_SET = 'RECEIVE_CHARACTER_SET';