export const RECEIVE_JOB_DATA = 'RECEIVE_JOB_DATA';
export const RECEIVE_ACTION_DATA = 'RECEIVE_ACTION_DATA';
export const RECEIVE_JOB_ACTIONS = 'RECEIVE_JOB_ACTIONS';

export const RECEIVE_CHARACTER_SET = 'RECEIVE_CHARACTER_SET';
export const SAVE_CHARACTER_SET = 'SAVE_CHARACTER_SET';
export const REMOVE_CHARACTER_SET = 'REMOVE_CHARACTER_SET';

export const RECEIVE_SETS = 'RECEIVE_SETS';

export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const UNAUTHENTICATE_USER = 'UNAUTHENTICATE_USER';

export const RETRIEVE_USER_INFO = 'RETRIEVE_USER_INFO';
export const UPDATE_USER_NAME = 'UPDATE_USER_NAME';